---
- hosts: all
  gather_facts: no
  pre_tasks:
    - raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
  sudo: yes
  sudo_user: root
  remote_user: vagrant
  vars:
    - update_apt_cache: yes
  roles:
    - role: erlang
      tags: erlang
    - role: elixir
      tags: elixir
    - role: phoenix
      tags: phoenix
    - role: postgresql
      tags: postgresql
